application:
  port: 8000
  host: 0.0.0.0
  # You need to set the `APP_APPLICATION__HMAC_SECRET` environment variable
  # on Digital Ocean as well for production!
  hmac_secret: "long-and-very-secret-random-key-needed-to-verify-message-integrity"
database:
  host: "localhost"
  port: 5432
  username: "ash"
  password: "tyson"
  database_name: "newsletter"
  require_ssl: false
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
redis_uri: "redis://127.0.0.1:6379"

#postgresql://ash:tyson@localhost:5432/newsletter
